### ISSUE TITLE
"anchor trusted" -> "anchor apple generic"

### ISSUE THREAD

**Issue by xnyhps** [theevilbit/Shield#1]
The connection to the XPC helper is validated here:

https://github.com/theevilbit/Shield/blob/3f892fad83520cd25c9e437c38fe3d1e664d4ef6/Extension/ShieldExtension.m#L112

This results in the requirement string:

```
anchor trusted and identifier "com.csaba.fitzl.shield" and certificate leaf[subject.OU] = "33YRLYRBYV"
```

According to [Apple's documentation](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html), the "anchor" syntax can be used as:

* `anchor apple`: Apple's own code
* `anchor apple generic`: Apple's own code and certificates issued by Apple to Apple Developers
* `anchor trusted`: signed by a code signing certificate that is trusted according to the system's Trust Settings database

Almost all applications I've seen that use a requirement string for validating an XPC connection use `anchor apple generic`. Shield is one of the few apps I found that use `anchor trusted`.

If I understand the documentation correctly, any code signing certificate issued by one of the system trusted roots could be used if it has an OrganizationalUnit (OU) of "33YRLYRBYV". Obviously, Apple would not issue such a certificate to another developer, but other roots might. Because the OU field typically refers to a unit in a company, it is very likely that it would be possible to obtain a code signing certificate with an arbitrary value in that field. (Because code signing certificates are not free, I have not actually tried that.) With that certificate it would be possible to sign apps that can communicate with the extension.

**Comment by theevilbit** [comment]
Thanks! Fixed!
