### ISSUE TITLE
Shield Preferences: Confusing Preference Title

### ISSUE THREAD

**Issue by 0xmachos** [theevilbit/Shield#10]
This is a tiny nitpick issue. 

In Shield's Preferences the title of the switch which enables or disables shield is "start/ stop" which is the opposite from the toggle position. When the toggle switch is to the right Shield is started not stopped. 

The `title` string below
https://github.com/theevilbit/Shield/blob/4fc0af77b90d021904067d0823d67fd4d88d0b0b/Shield/Base.lproj/MainMenu.xib#L778

could be changed to 
```
title="stop / start system extension"
```

to correct this.

**Comment by theevilbit** [comment]
I will change it to "Enabled"

**Comment by theevilbit** [comment]
Fixed in https://github.com/theevilbit/Shield/commit/13c48e01fc9cf1ccb4f062c2dfbf000ef648239d
