### ISSUE TITLE
Catalina: can not start (possibly can't install system extension)

### ISSUE THREAD

**Issue by JayBrown** [theevilbit/Shield#2]
On Catalina, the Shield monitor won't start. When I click on "Install System Extension", nothing happens, no password prompt. When I click on "Uninstall System Extension", I get the password prompt, but then, when trying to install again, nothing happens.

**Comment by theevilbit** [comment]
What does `systemextensionsctl list` show?

**Comment by JayBrown** [comment]
Only the AdGuard system extension, not Shield.

I'm also not asked to unblock the Shield system extension in  System Preferences > Security & Privacy … so it seems like the system extension never installs in the first place.

**Comment by theevilbit** [comment]
I retested it on a Catalina VM, and it works for me. What is your Catalina version? If you open the "Console.app" and filter for "shield", do you see any errors, when clicking "Install System Extension"?

**Comment by theevilbit** [comment]
You need macOS 10.15.4+

**Comment by JayBrown** [comment]
I found the reason. I had installed Shield in `~/Applications/Utilities`. I restarted and installed it into the global `/Applications` directory, and now it's working. :)

**Comment by theevilbit** [comment]
Awesome! 👍
