### ISSUE TITLE
Catalina: "Blocking Mode" displayed even when disabled

### ISSUE THREAD

**Issue by JayBrown** [theevilbit/Shield#3]
Catalina: Shield displays the mode as "Blocking", even when "blocking mode" is disabled in Shield Preferences.

**Comment by theevilbit** [comment]
Was the extension installed properly?  For that to be properly refreshed/shown, the extension must be installed properly.

**Comment by JayBrown** [comment]
Yes, same thing as with the other issue. Closing this then.
