### ISSUE TITLE
Catalina: Shield forgets settings after quit & relaunch

### ISSUE THREAD

**Issue by JayBrown** [theevilbit/Shield#4]
Catalina: Shield forgets the user settings in preferences, i.e. the "injection protection settings", after quit and relaunch.

**Comment by theevilbit** [comment]
Was the extension installed properly? Your first bug suggests that it wasn't. If it's not installed, the preferences aren't saved.

**Comment by JayBrown** [comment]
Ah, OK… I suspected it had something to do with that. Closing this issue then.
