### ISSUE TITLE
Catalina: Shield disabled after wake from deep sleep

### ISSUE THREAD

**Issue by JayBrown** [theevilbit/Shield#7]
I use deep sleep (a.k.a. hibernation) instead of regular sleep, including destruction of FileVault keys, i.e. RAM content is written to disk.

After installing Shield (and having it run at time of deep sleep), strange things happen during wake after entering my FileVault password:

* waking from this state takes very long, almost one minute
* this includes a spinning beachball on the login screen
* Shield itself is disabled afterwards

This disabling of Shield only seems to affect the app itself, not the system extension. Trying stop and restart from the menu doesn't work. I actually have to quit and relaunch Shield, and only then start the watcher. Only then the Shield notifications will return.

That's why I think that it has nothing to do with the system extension. But maybe—because macOS unloads the system extension before hibernation—the Shield app doesn't know what to do when the SEXT is gone without an actual command from the app itself, and before it can do or find anything, macOS will start hibernation, and then, at wake, Shield tries to continue that process, but eventually fails or times out, ergo spinning beach ball. (?)

To replicate, here are my pm settings (2018 MBP, i9, maxed-out, Catalina 10.15.7):

```
❯ pmset -g
System-wide power settings:
 DestroyFVKeyOnStandby		1
Currently in use:
 standby              1
 standbydelaylow      30
 womp                 0
 halfdim              0
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 gpuswitch            2
 powernap             0
 networkoversleep     0
 disksleep            25
 standbydelayhigh     30
 sleep                5
 hibernatemode        25
 ttyskeepawake        0
 displaysleep         5
 tcpkeepalive         0
 highstandbythreshold 100
 acwake               0
 lidwake              0
```

**Comment by JayBrown** [comment]
Made a test: stopped Shield before deep sleep, and that resulted in a normal wake procedure… but that was just one test. Will need to repeat it a couple of times.

**Comment by theevilbit** [comment]
I did some change in the logic. Not sure if it made an impact on this, but can you retest it?

**Comment by JayBrown** [comment]
I just had the first wake from deep sleep, and Shield, which I had kept enabled, was running fine afterwards, and the wake didn't have any delay. I will monitor this further, but will close the issue for now. (There are still glitches at wake from deep sleep, namely improper wake and consecutive "re-sleep", but those occur even with Shield disabled, so I suspect it's a macOS bug.)
