### ISSUE TITLE
Whitelist functionality would need learning mode

### ISSUE THREAD

**Issue by JayBrown** [theevilbit/Shield#8]
I have lots of background processes spawning DYLD_INSERT_LIBRARIES notifications… simply launching iTerm or updating Homebrew will spawn those, and lots of my own scripts & agents too, and also third-party software like fs protection updating the database in `/usr/local`.

Can't say what happens during boot.

So I believe that a whitelist functionality should come with some kind of learning mode that persists across logouts or reboots, so the user can run Shield in that state for a day or half a day, and when the user stops learning mode, Shield will present all the recorded events for the user to approve or block.

PS: learning mode should still include notifications, so in effect it would be standard monitor mode plus learning mode.

**Comment by theevilbit** [comment]
Good idea! Once I implement whitelisting I can do this.

During boot shield is not active, also it doesn't autostart yet at all, and Apple binaries are all excluded.

**Comment by theevilbit** [comment]
Will work in 1.0. Implemented, but still working on other stuff. Learning mode won't do alerting, it will be silent - but you should be able to edit/review the list later (still working on that). Also it will be effective only when in non-blocking mode.

**Comment by theevilbit** [comment]
Done with https://github.com/theevilbit/Shield/commit/984354d822da31e21d1df9e7f5408a716703e8c5
