### ISSUE TITLE
Invalid UTF8 in environment variable raises exception

### ISSUE THREAD

**Issue by xnyhps** [theevilbit/Shield#9]
I think the if-statement on line 256 was intended to refer to `environment` instead of `env`:

https://github.com/theevilbit/Shield/blob/f8666ca14762f692e7f7ff604e2f32ff9addf7e1/procmon/Process.m#L254-L260

`env` shouldn't ever be `nil`, because it is initialized as an `NSMutableArray`.

If an environment variable contains invalid UTF8 (which is entirely legal on macOS), then `convertStringToken` will return `nil`. Due to the wrong check, a `nil` object will be added to an `NSMutableArray`, which raises an exception (likely crashing the process).

See also https://github.com/objective-see/LuLu/issues/305 for a similar bug.

**Comment by theevilbit** [comment]
Thanks for reporting! I used the same code base :D Will get it fixed in the next release.

**Comment by theevilbit** [comment]
Fixed with https://github.com/theevilbit/Shield/commit/4fc0af77b90d021904067d0823d67fd4d88d0b0b
